### ISSUE TITLE
CCA Tools are failing to product SIPs and description CSVs

### ISSUE THREAD

**Issue by fneggers** [CCA-Public/cca-tools#4]
Our BitCurator environment (dedicated PC) accesses data on a network drive. BitCurator tools can access the data, but when the CCA tools execute an action, data are not processed and no result data are returned. Could this be a network problem (or a Bitcurator or network configuration problem)? Or should it be solved on the level of the CCA tools?

**Comment by tw4l** [comment]
Thank you for reporting this @fneggers! The issue appears to be due to changes in the [DFXML Python bindings](https://github.com/simsong/dfxml/tree/master/python/dfxml). The CCA tools were using the system-installed version of these binds in BitCurator and so the change in filepaths resulted in errors in the CCA Tools.

I will be submitting a series of pull requests shortly which resolves the issue for each of the CCA Tools.

**Comment by tw4l** [comment]
This issue has been resolved via the three above linked pull requests.
